### ISSUE TITLE
Add social discussion icons

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#10]
I'd like to be able to configure which social discussion/sharing icon links I want to display in the `layouts/_default/single.html` template. I think a setting in the site's config.yaml would be a good way to control this. I'd like a list like

```yaml
shareIcons:
  - twitter
  - reddit
```

A design example from rollout.io's blog for inspiration:

![image](https://user-images.githubusercontent.com/279875/43926646-f92f9a36-9bf8-11e8-976f-49a22eac1011.png)

```html
<ul class="post-share">
			<li class="post-share-title">Share:</li>
			<li><a href="http://twitter.com/share?text=Database+Migration%3A+What+It+Is+and+How+to+Do+It&amp;url=https://rollout.io/blog/database-migration/" onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;" title="Twitter" class="socialdark twitter"><i class="fa fa-twitter"></i></a></li>
			<li><a href="https://www.facebook.com/sharer/sharer.php?u=https://rollout.io/blog/database-migration/" onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;" title="Facebook" class="socialdark facebook"><i class="fa fa-facebook"></i></a></li>
			<li><a href="https://plus.google.com/share?url=https://rollout.io/blog/database-migration/" onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;" title="Google Plus" class="socialdark google"><i class="fa fa-google-plus"></i></a></li>
			<li><a href="http://www.reddit.com/submit?url=https://rollout.io/blog/database-migration/&amp;title=Database+Migration%3A+What+It+Is+and+How+to+Do+It" onclick="window.open(this.href, 'reddit-share', 'width=490,height=530');return false;" title="Reddit" class="socialdark reddit"><i class="fa fa-reddit"></i></a></li>
			<li><a href="http://pinterest.com/pin/create/button/?url=https://rollout.io/blog/database-migration/&amp;description=Database+Migration%3A+What+It+Is+and+How+to+Do+It" onclick="window.open(this.href, 'pinterest-share', 'width=490,height=530');return false;" title="Pinterest" class="socialdark pinterest"><i class="fa fa-pinterest"></i></a></li>
			<li><a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=https://rollout.io/blog/database-migration/&amp;title=Database+Migration%3A+What+It+Is+and+How+to+Do+It" onclick="window.open(this.href, 'linkedin-share', 'width=490,height=530');return false;" title="LinkedIn" class="socialdark linkedin"><i class="fa fa-linkedin"></i></a></li>
		</ul>
```

**Comment by xaprb** [comment]
done; just add to the menus in the site config. Example config.yaml:

```yaml

menu:
   main:
   - name: Talks
     title: Talks
     url: /talks/
   social:
   - name: linkedin
     title: "fab fa-linkedin"
     url: "https://linkedin.com/in/xaprb"
   - name: twitter
     title: "fab fa-twitter-square"
     url: "https://twitter.com/xaprb"
   - name: github
     title: "fab fa-github-square"
     url: "https://github.com/xaprb"
```
