### ISSUE TITLE
Make the layout configurable

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#5]
I'd like users to be able to change the site's layout options using their `config.yaml` settings. The [story](https://html5up.net/story) theme this theme is based on allows that and it's simple CSS. That page is self-documenting, with a long list of the options, which typically include "style, scheme, color, orientation, content alignment, and image position, as well as assign it an optional onload or onscroll transition modifier..." The HTML looks like this, for example:

    class="spotlight style1 orient-left content-align-left image-position-center onscroll-image-fade-in"

There's a ton of flexibility. If users of this theme could simply put that into their config.yaml and the theme's templates could inject it (or a default, if nothing is in the config.yaml), it might look like this:

````yaml
story:
  default_list_template: "spotlight style1 orient-left content-align-left image-position-center onscroll-image-fade-in"
  related_content_template: "..."
````

There's a bunch of places where I've built the theme with my own preferences, but I could easily see someone else wanting it done differently.
