### ISSUE TITLE
[BUG] Printing slides to PDF makes ugly shadows

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#84]
When printing slides to PDF with Chrome, text shadows are rendered without blur.

![xaprb_2019-Mar-23](https://user-images.githubusercontent.com/279875/54871470-93ae2580-4d8a-11e9-8ea4-1d6ed881f1ce.jpg)

Reading [here](https://stackoverflow.com/questions/13975198/text-shadow-and-box-shadow-while-printing-chrome#21139139) I found a solution that seems to work, 

```css
.thing {
    -webkit-print-color-adjust:exact;
    -webkit-filter:opacity(1);
}
```

The related bug seems to be https://code.google.com/p/chromium/issues/detail?id=174583.

This wasn't a problem until a month or so ago, but a Chrome upgrade seems to have triggered it. So perhaps it's a different bug, but at least I have a workaround that works.
